#!/usr/bin/env bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.
# This can mean RubyGems, npm packages, Homebrew packages, Ruby versions, Git submodules, etc.
# The goal is to make sure all required dependencies are installed.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if [ -f ".node-version" ] && [ -z "$(nodenv version-name 2>/dev/null)" ]; then
	echo "==> Installing node"
	nodenv install --skip-existing
fi

if [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
    echo "==> Installing Ruby…"
    rbenv install --skip-existing
    which bundle >/dev/null 2>&1 || {
        gem install bundler
        rbenv rehash
    }
fi

if [ -f "package.json" ]; then
	echo "==> Installing npm dependencies..."
	npm install --silent --no-spin
fi

if [ -f "Gemfile" ]; then
    echo "==> Installing gem dependencies…"
    bundle check --path vendor/gems >/dev/null 2>&1  || {
        bundle install --path vendor/gems --quiet --without production
    }
fi

if [ -f "docker-compose.yml" ]; then
	script/rebuild
	script/compose pull --ignore-pull-failures
fi
