version: '3'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on: 
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=web_app_dev
      - POSTGRES_USER=web_app
      - POSTGRES_PASSWORD=web_app
volumes:
  pgdata: